# -*- coding: utf-8 -*-
"""Quizapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBdg1zX__Kf0yOAzLhPRxE-Wog97TlEy
"""

# Commented out IPython magic to ensure Python compatibility.
# # prompt: make app with streamlit with ridge model generate the python codes
# 
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import pickle
# 
# # Load the trained Ridge model
# filename = 'ridge_model.pkl'
# loaded_model = pickle.load(open(filename, 'rb'))
# 
# # Create a title for your app
# st.title("Monthly Revenue Prediction App")
# 
# # Create input fields for user data
# st.header("Enter Customer Data:")
# total_orders = st.number_input("Total Orders:")
# avg_order_value = st.number_input("Average Order Value:")
# customer_lifetime_value = st.number_input("Customer Lifetime Value:")
# average_order_frequency = st.number_input("Average Order Frequency:")
# days_since_last_order = st.number_input("Days Since Last Order:")
# 
# # Create a button to trigger prediction
# if st.button("Predict Monthly Revenue"):
#     # Create a DataFrame with the user's input
#     input_data = pd.DataFrame({
#         'total_orders': [total_orders],
#         'avg_order_value': [avg_order_value],
#         'customer_lifetime_value': [customer_lifetime_value],
#         'average_order_frequency': [average_order_frequency],
#         'days_since_last_order': [days_since_last_order]
#     })
# 
#     # Make a prediction using the loaded model
#     prediction = loaded_model.predict(input_data)[0]
# 
#     # Display the prediction
#     st.header("Predicted Monthly Revenue:")
#     st.write(f"${prediction:.2f}")
#